version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Используем Dockerfile для разработки
    volumes:
      - ./app:/app  # Монтируем директорию app для разработки
    command: make dev  # Команда для запуска в режиме разработки