version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production  # Используем Dockerfile.production для тестов и продакшена
    image: mishaikon/devops-for-programmers-project-74  # Укажите имя вашего Docker Hub репозитория
    ports:
      - "8080:8080"