---
- name: Install and configure Nginx
  hosts: webservers
  become: yes
  vars:
    nginx_port: 80  # Порт по умолчанию
    root_dir: /usr/share/nginx/html  # Корневая директория по умолчанию

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create root directory
      file:
        path: "{{ root_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy HTML file
      copy:
        src: files/index.html
        dest: "{{ root_dir }}/index.html"
        owner: root
        group: root
        mode: '0644'

    - name: Configure Nginx using template
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
