version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    command: make dev

  caddy:
    image: caddy:latest
    ports:
      - "80:80"  # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile  # Монтируем конфигурационный файл
    depends_on:
      - app  # Зависимость от сервиса app
